### ISSUE TITLE
Data format of Scenario_1

### ISSUE THREAD

**Issue by jarvisyjw** [Viky397/TorWICDataset#1]
Hi, Thanks so much for releasing this dataset. However, I am wondering if there is something wrong with `Scenarios_1-1.zip` and `Scenarios_1_bags.zip`. For `Scenarios_1-1.zip`, there is no imu.txt, odom.txt poses.txt as expected and for `Scenarios_1_bags.zip` the zip file can not be unzipped.

**Comment by jarvisyjw** [comment]
> Hi, Thanks so much for releasing this dataset. However, I am wondering if there is something wrong with `Scenarios_1-1.zip` and `Scenarios_1_bags.zip`. For `Scenarios_1-1.zip`, there is no imu.txt, odom.txt poses.txt as expected and for `Scenarios_1_bags.zip` the zip file can not be unzipped.

Also, for sequence Scenario_1-8, Scenario_1-9, inside their file folder exist Scenario_1-9, Scenario_1-10. But as far as I have inspected from the content, they should belong to the correct sequence but with an incorrect file name.

**Comment by Viky397** [comment]
Hello, sorry for the delayed response. We will address these issues and post an update here! Thank you for bringing them up.

**Comment by Viky397** [comment]
Dataset has been updated.
