### ISSUE TITLE
Datasets are by invitation only

### ISSUE THREAD

**Issue by adthoms** [Viky397/TorWICDataset#2]
Hello Viky, can the links to the dataset be made public? Right now they are by invitation only. Thank you.

**Comment by Viky397** [comment]
Hello, I've just double checked, and all the links should be public: 
https://drive.google.com/drive/folders/12-h2OPmlmxLk0Y9C3Hr5glkalUp66oEJ

**Comment by adthoms** [comment]
Thank you for the link, this works. The `Real-World Warehouse Scenario` links still give me the `You need access` request though.

**Comment by Viky397** [comment]
Correct. The real-world dataset link is in our Work in Progress section. It is a new dataset that will be released this summer.

The dataset from our 2022 POCD paper is here: https://github.com/Viky397/TorWICDataset#download-dataset
